load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "entity",
    srcs = [
        "ActivityTrackingEntity.go",
        "AiChatEntity.go",
        "AiChatMessageEntity.go",
        "ApihubApiKeyEntity.go",
        "BuildCleanupEntity.go",
        "BuildEntity.go",
        "BuildResultEntity.go",
        "BuilderNotificationsEntity.go",
        "BusinessMetric.go",
        "Changes.go",
        "ComparisonCleanupEntity.go",
        "DDLContractEntity.go",
        "EphemeralFileEntity.go",
        "ExportResultEntity.go",
        "FavoritesEntities.go",
        "IntegrationEntity.go",
        "InternalDocumentEntity.go",
        "LockEntity.go",
        "MCPContractEntity.go",
        "Metadata.go",
        "MetricsEntity.go",
        "MigrationEntity.go",
        "OperationEntity.go",
        "OperationsGroupEntity.go",
        "PackageExportConfigEntity.go",
        "PackageMemberRoleEntity.go",
        "PersonalAccessTokenEntity.go",
        "PrincipalEntity.go",
        "PublishedEntities.go",
        "SearchEntity.go",
        "SoftDeletedDataCleanupEntity.go",
        "SourcesUpdateTrackingEntity.go",
        "SystemRoleEntity.go",
        "SystemStatsEntity.go",
        "TransitionEntity.go",
        "UnreferencedDataCleanupEntity.go",
        "UserAvatarEntity.go",
        "UserEntity.go",
        "ValidationEntities.go",
        "VersionCleanupEntity.go",
    ],
    importpath = "github.com/Netcracker/qubership-apihub-backend/qubership-apihub-service/entity",
    visibility = ["//visibility:public"],
    deps = [
        "//qubership-apihub-backend/qubership-apihub-service/utils",
        "//qubership-apihub-backend/qubership-apihub-service/view",
        "@com_github_google_uuid//:go_default_library",
        "@com_github_iancoleman_orderedmap//:go_default_library",
        "@com_github_sirupsen_logrus//:go_default_library",
    ],
)
