load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "repository",
    srcs = ["MigrationRunRepository.go"],
    importpath = "github.com/Netcracker/qubership-apihub-backend/qubership-apihub-service/migration/repository",
    visibility = ["//visibility:public"],
    deps = [
        "//qubership-apihub-backend/qubership-apihub-service/db",
        "//qubership-apihub-backend/qubership-apihub-service/migration/entity",
        "//qubership-apihub-backend/qubership-apihub-service/migration/view",
        "@com_github_go_pg_pg_v10//:go_default_library",
    ],
)
