load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "view",
    srcs = [
        "ActivityTracking.go",
        "Admin.go",
        "AiChat.go",
        "ApiConfig.go",
        "ApiKey.go",
        "ApihubApiKey.go",
        "AsyncAPIOperation.go",
        "Audience.go",
        "Build.go",
        "BusinessMetric.go",
        "CommonOperation.go",
        "Comparison.go",
        "ContentData.go",
        "DDLContract.go",
        "DbCredentials.go",
        "Document.go",
        "Excel.go",
        "Export.go",
        "ExternalMetadata.go",
        "GraphQLOperation.go",
        "Integration.go",
        "InternalDocument.go",
        "Job.go",
        "LdapAttributes.go",
        "MCP.go",
        "MCPContract.go",
        "Minio.go",
        "Monitoring.go",
        "OperationGroup.go",
        "Package.go",
        "PackageExportConfig.go",
        "PackageMemberRole.go",
        "PersonalAccessToken.go",
        "Portal.go",
        "Principal.go",
        "ProtobufOperation.go",
        "PublishNotification.go",
        "PublishV2.go",
        "PublishedContent.go",
        "PublishedVersion.go",
        "RestOperation.go",
        "Role.go",
        "RolePermission.go",
        "Search.go",
        "ShortcutType.go",
        "Status.go",
        "SystemInfo.go",
        "SystemStats.go",
        "Transition.go",
        "User.go",
        "Validation.go",
        "Version.go",
        "VersionStatus.go",
    ],
    importpath = "github.com/Netcracker/qubership-apihub-backend/qubership-apihub-service/view",
    visibility = ["//visibility:public"],
    deps = [
        "//qubership-apihub-backend/qubership-apihub-service/exception",
        "//qubership-apihub-backend/qubership-apihub-service/security/idp",
        "//qubership-apihub-backend/qubership-apihub-service/utils",
        "@com_github_iancoleman_orderedmap//:go_default_library",
        "@com_github_mark3labs_mcp_go//mcp:go_default_library",
    ],
)
