load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "repository",
    srcs = [
        "ActivityTrackingRepository.go",
        "AiChatRepository.go",
        "AiChatRepositoryPG.go",
        "ApihubApiKeyRepository.go",
        "ApihubApiKeyRepositoryPG.go",
        "BuildCleanupRepository.go",
        "BuildRepository.go",
        "BuildResultRepository.go",
        "BusinessMetricRepository.go",
        "ComparisonCleanupRepository.go",
        "DDLContractRepository.go",
        "EphemeralFileRepository.go",
        "ExportResultRepository.go",
        "FavoritesRepository.go",
        "FavoritesRepositoryPG.go",
        "LockRepository.go",
        "MCPContractRepository.go",
        "MetricsRepository.go",
        "OperationRepository.go",
        "PackageExportConfigRepository.go",
        "PersonalAccessTokenRepository.go",
        "PublishedRepository.go",
        "PublishedRepositoryPG.go",
        "RoleRepository.go",
        "SoftDeletedDataCleanupRepository.go",
        "SystemStatsRepository.go",
        "TransitionRepository.go",
        "UnreferencedDataCleanupRepository.go",
        "UserRepository.go",
        "UserRepositoryPG.go",
        "VersionCleanupRepository.go",
    ],
    importpath = "github.com/Netcracker/qubership-apihub-backend/qubership-apihub-service/repository",
    visibility = ["//visibility:public"],
    deps = [
        "//qubership-apihub-backend/qubership-apihub-service/context",
        "//qubership-apihub-backend/qubership-apihub-service/db",
        "//qubership-apihub-backend/qubership-apihub-service/entity",
        "//qubership-apihub-backend/qubership-apihub-service/exception",
        "//qubership-apihub-backend/qubership-apihub-service/metrics",
        "//qubership-apihub-backend/qubership-apihub-service/migration/entity",
        "//qubership-apihub-backend/qubership-apihub-service/service/cleanup/logger",
        "//qubership-apihub-backend/qubership-apihub-service/utils",
        "//qubership-apihub-backend/qubership-apihub-service/view",
        "@com_github_go_pg_pg_v10//:go_default_library",
        "@com_github_go_pg_pg_v10//orm:go_default_library",
        "@com_github_google_uuid//:go_default_library",
        "@com_github_pkg_errors//:go_default_library",
        "@com_github_sirupsen_logrus//:go_default_library",
        "@org_golang_x_net//context:go_default_library",
    ],
)
