import { DIFF_META_KEY, DIFFS_AGGREGATED_META_KEY } from '@netcracker/qubership-apihub-api-diff'
import { HASH_FLAG, INLINE_REFS_FLAG, ORIGINS_SYMBOL, SYNTHETIC_TITLE_FLAG } from '@netcracker/qubership-apihub-api-processor'

export const INTERNAL_DOCUMENT_STRING_SYMBOL_MAPPING = new Map([
  ['SYNTHETIC_TITLE_FLAG', SYNTHETIC_TITLE_FLAG],
  ['ORIGINS_SYMBOL', ORIGINS_SYMBOL],
  ['HASH_FLAG', HASH_FLAG],
  ['INLINE_REFS_FLAG', INLINE_REFS_FLAG],
  ['DIFF_META_KEY', DIFF_META_KEY],
  ['DIFFS_AGGREGATED_META_KEY', DIFFS_AGGREGATED_META_KEY],
])
