load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "context",
    srcs = ["SecurityContext.go"],
    importpath = "github.com/Netcracker/qubership-apihub-backend/qubership-apihub-service/context",
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_shaj13_go_guardian_v2//auth:go_default_library",
    ],
)
