load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "view",
    srcs = [
        "report.go",
        "request.go",
    ],
    importpath = "github.com/Netcracker/qubership-apihub-backend/qubership-apihub-service/migration/view",
    visibility = ["//visibility:public"],
    deps = ["//qubership-apihub-backend/qubership-apihub-service/view"],
)
