load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "repository",
    srcs = [
        "agent.go",
        "namespace_security.go",
    ],
    importpath = "github.com/Netcracker/qubership-apihub-agents-backend/repository",
    visibility = ["//visibility:public"],
    deps = [
        "//qubership-apihub-agents-backend/qubership-apihub-agents-backend/db",
        "//qubership-apihub-agents-backend/qubership-apihub-agents-backend/entity",
        "//qubership-apihub-agents-backend/qubership-apihub-agents-backend/view",
        "@com_github_go_pg_pg_v10//:go_default_library",
    ],
)
